export const products = [
  {
    id: 1,
    categoryId: 1,
    title: '"Cheval Punk Bandana" boxy fit shirt',
    slug: 1,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1999.0,
      salePrice: 1744.75,
      saleProfit: 322.5,
      shippingType: 3,
      cost: 100.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 32,
      AE: 132,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 2,
    categoryId: 1,
    title: '"Detail H" polo shirt',
    slug: 2,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1960.0,
      salePrice: 1900.75,
      saleProfit: 300.5,
      shippingType: 2,
      cost: 150.4,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 3,
    categoryId: 1,
    title: '"Devant cuir empreinte sellier" overshirt',
    slug: 3,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 2999,
      salePrice: 2100,
      saleProfit: 30.76,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 4,
    categoryId: 1,
    title: 'Fitted shirt with Louis collar',
    slug: 4,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 3987,
      salePrice: 3000.65,
      saleProfit: 239.65,
      shippingType: 3,
      cost: 90.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 5,
    categoryId: 1,
    title: '"H" sporty fit embroidered shirt',
    slug: 5,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1565.5,
      salePrice: 1250,
      saleProfit: 239,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 6,
    categoryId: 1,
    title: '"H" embroidered T-shirt',
    slug: 6,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1899.99,
      salePrice: 1699,
      saleProfit: 198,
      shippingType: 2,
      cost: 198.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 7,
    categoryId: 1,
    title: '"Parcours Sans Faute Decadre" t-shirt',
    slug: 7,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 789.99,
      salePrice: 709.99,
      saleProfit: 102.4,
      shippingType: 3,
      cost: 97,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 8,
    categoryId: 1,
    title: '"Piqures sellier" t-shirt',
    slug: 8,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1570,
      salePrice: 1498.5,
      saleProfit: 113.9,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 9,
    categoryId: 1,
    title: 'Polo shirt with pocket',
    slug: 9,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 5999,
      salePrice: 3999,
      saleProfit: 455.5,
      shippingType: 3,
      cost: 398,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 10,
    categoryId: 1,
    title: 'Saint Germain fitted pants',
    slug: 10,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 2404,
      salePrice: 2199,
      saleProfit: 188.5,
      shippingType: 3,
      cost: 305.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 11,
    categoryId: 1,
    title: 'Straight cut jeans',
    slug: 11,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 2832.99,
      salePrice: 2100.6,
      saleProfit: 78,
      shippingType: 2,
      cost: 87.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 12,
    categoryId: 2,
    title: '18-3-7 scarf 90',
    slug: 12,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 499,
      salePrice: 419.99,
      saleProfit: 53,
      shippingType: 3,
      cost: 24.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 13,
    categoryId: 2,
    title: 'A Toute Berline ! leather eyelet scarf 70',
    slug: 13,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 495.5,
      salePrice: 399,
      saleProfit: 34,
      shippingType: 2,
      cost: 67,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 14,
    categoryId: 2,
    title: 'Brides de Gala Tattoo Cotton Appliqué scarf 90',
    slug: 14,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 998,
      salePrice: 799.9,
      saleProfit: 100,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 15,
    categoryId: 2,
    title: 'Emile et Une Nuit scarf 90',
    slug: 15,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 876.5,
      salePrice: 799.5,
      saleProfit: 138,
      shippingType: 3,
      cost: 98,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 16,
    categoryId: 2,
    title: 'Emile et Une Nuit scarf 90',
    slug: 16,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1270,
      salePrice: 1174,
      saleProfit: 398.5,
      shippingType: 3,
      cost: 230,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 17,
    categoryId: 2,
    title: 'Figures Libres Twilly',
    slug: 17,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 764,
      salePrice: 690.5,
      saleProfit: 90.5,
      shippingType: 2,
      cost: 56.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 18,
    categoryId: 2,
    title: 'Mystere au 24 scarf 90',
    slug: 18,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 999,
      salePrice: 599,
      saleProfit: 10,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 19,
    categoryId: 2,
    title: 'Rayee H stole',
    slug: 19,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199,
      salePrice: 179,
      saleProfit: 32.5,
      shippingType: 2,
      cost: 23.9,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 20,
    categoryId: 2,
    title: 'Ready… Go! scarf 45',
    slug: 20,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 478,
      salePrice: 399,
      saleProfit: 34.9,
      shippingType: 3,
      cost: 45,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 21,
    categoryId: 2,
    title: 'Stately Wheels scarf 90',
    slug: 21,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1950.99,
      salePrice: 1678,
      saleProfit: 390.5,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 22,
    categoryId: 3,
    title: '"Bolduc au Carre" micro t-shirt',
    slug: 22,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 699,
      salePrice: 499,
      saleProfit: 73.5,
      shippingType: 3,
      cost: 40.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 23,
    categoryId: 3,
    title: '"Coaching Deja Vu" short-sleeve twillaine sweater',
    slug: 23,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 5050,
      salePrice: 4990,
      saleProfit: 230.5,
      shippingType: 2,
      cost: 90,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },

  {
    id: 24,
    categoryId: 3,
    title: '"Coaching" long-sleeve cardigan',
    slug: 24,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1990.0,
      salePrice: 1740.75,
      saleProfit: 320.5,
      shippingType: 3,
      cost: 200.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 25,
    categoryId: 3,
    title: '"Coaching Remix" maxi t-shirt',
    slug: 25,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 798,
      salePrice: 684.5,
      saleProfit: 97.5,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 26,
    categoryId: 3,
    title: 'Embroidered long poncho vest.webp',
    slug: 26,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1289,
      salePrice: 999,
      saleProfit: 132,
      shippingType: 3,
      cost: 79.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 27,
    categoryId: 3,
    title: '"En Desordre Finesse" belted caftan',
    slug: 27,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1476.5,
      salePrice: 1376.5,
      saleProfit: 341,
      shippingType: 3,
      cost: 87.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 28,
    categoryId: 3,
    title: 'Fit sweatshirt',
    slug: 28,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 2299,
      salePrice: 174.75,
      saleProfit: 348,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 29,
    categoryId: 3,
    title: 'Jacket with leather detail',
    slug: 29,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 5999,
      salePrice: 4599,
      saleProfit: 765.5,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 30,
    categoryId: 3,
    title: 'Micro shirt',
    slug: 30,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1365,
      salePrice: 1199,
      saleProfit: 298,
      shippingType: 3,
      cost: 102.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 31,
    categoryId: 3,
    title: '"Mors a Jouets" embroidered long-sleeve sweater',
    slug: 31,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 2465.99,
      salePrice: 1899,
      saleProfit: 55,
      shippingType: 2,
      cost: 144,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 32,
    categoryId: 3,
    title: '"Mors a Jouets" t-shirt',
    slug: 32,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 999,
      salePrice: 950,
      saleProfit: 210,
      shippingType: 2,
      cost: 41,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 33,
    categoryId: 3,
    title: '"Mosaique" prairie dress',
    slug: 33,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 4849.99,
      salePrice: 4400,
      saleProfit: 287.65,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 34,
    categoryId: 4,
    title: 'Alessandro loafer',
    slug: 34,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 7999,
      salePrice: 7100,
      saleProfit: 2897,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 35,
    categoryId: 4,
    title: 'Bouncing sneaker',
    slug: 35,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 4998.99,
      salePrice: 4599,
      saleProfit: 500,
      shippingType: 3,
      cost: 200,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 36,
    categoryId: 4,
    title: 'Chypre sandal',
    slug: 36,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1123,
      salePrice: 999.99,
      saleProfit: 35,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 37,
    categoryId: 4,
    title: 'Deep sneaker',
    slug: 37,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 3899,
      salePrice: 3650,
      saleProfit: 602,
      shippingType: 3,
      cost: 319,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 38,
    categoryId: 4,
    title: 'Eze 30 sandal',
    slug: 38,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1900,
      salePrice: 1740.5,
      saleProfit: 150,
      shippingType: 2,
      cost: 165,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 39,
    categoryId: 4,
    title: 'Fresh ankle boot',
    slug: 39,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 5870,
      salePrice: 4999,
      saleProfit: 1220,
      shippingType: 3,
      cost: 145.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 40,
    categoryId: 4,
    title: 'Heros sneaker',
    slug: 40,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 3799,
      salePrice: 3265.8,
      saleProfit: 349,
      shippingType: 2,
      cost: 98,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 41,
    categoryId: 4,
    title: 'Jimmy sneaker',
    slug: 41,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 2550,
      salePrice: 2399.99,
      saleProfit: 1876,
      shippingType: 2,
      cost: 234,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 42,
    categoryId: 4,
    title: 'Job loafer',
    slug: 42,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 5100,
      salePrice: 4299,
      saleProfit: 2100,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 43,
    categoryId: 4,
    title: 'Jupiter sandal',
    slug: 43,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1765,
      salePrice: 1599.5,
      saleProfit: 265,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 44,
    categoryId: 4,
    title: 'Kelly ballet flat',
    slug: 44,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 599,
      salePrice: 549.5,
      saleProfit: 29,
      shippingType: 3,
      cost: 67.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 45,
    categoryId: 4,
    title: 'Kichu ballet flat',
    slug: 45,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 782.5,
      salePrice: 699,
      saleProfit: 54,
      shippingType: 2,
      cost: 19.99,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 46,
    categoryId: 4,
    title: 'Kristen sandal',
    slug: 46,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 1897.6,
      salePrice: 1567.6,
      saleProfit: 200,
      shippingType: 3,
      cost: 102.2,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 47,
    categoryId: 4,
    title: 'Oasis sandal',
    slug: 47,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 3105,
      salePrice: 2999,
      saleProfit: 398,
      shippingType: 2,
      cost: 76,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 48,
    categoryId: 4,
    title: 'Oz mule',
    slug: 48,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 4499,
      salePrice: 4149.5,
      saleProfit: 1000,
      shippingType: 3,
      cost: 200.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 49,
    categoryId: 5,
    title: 'Bonnie Lift beret',
    slug: 49,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 298,
      salePrice: 249.5,
      saleProfit: 26,
      shippingType: 3,
      cost: 32,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 50,
    categoryId: 5,
    title: 'Fred Punk H bucket hat',
    slug: 50,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 297.99,
      salePrice: 290,
      saleProfit: 35,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 51,
    categoryId: 5,
    title: 'Harper Emile Hermès bucket hat',
    slug: 51,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 650,
      salePrice: 499,
      saleProfit: 119,
      shippingType: 2,
      cost: 48.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 52,
    categoryId: 5,
    title: 'Harper Point Avalon bucket hat',
    slug: 52,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 823,
      salePrice: 599,
      saleProfit: 134,
      shippingType: 2,
      cost: 43.6,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 53,
    categoryId: 5,
    title: 'Ionis Stripes hat',
    slug: 53,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 780,
      salePrice: 720.99,
      saleProfit: 235,
      shippingType: 3,
      cost: 99,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 54,
    categoryId: 5,
    title: 'Jane Love bucket hat',
    slug: 54,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 999,
      salePrice: 799.5,
      saleProfit: 276,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 55,
    categoryId: 5,
    title: 'Julia Naoussa beanie',
    slug: 55,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 1199.2,
      saleProfit: 999,
      shippingType: 2,
      cost: 156.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 56,
    categoryId: 5,
    title: 'Nevada Etriers cap',
    slug: 56,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 743,
      salePrice: 550.75,
      saleProfit: 109,
      shippingType: 3,
      cost: 79,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 57,
    categoryId: 5,
    title: 'Nevada H Stripe cap',
    slug: 57,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 385,
      salePrice: 299,
      saleProfit: 71.4,
      shippingType: 3,
      cost: 87.3,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 58,
    categoryId: 5,
    title: 'Serena Lift cap',
    slug: 58,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 21.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
];
