export const products = [
  {
    id: 1,
    categoryId: 1,
    title: '"Cheval Punk Bandana" boxy fit shirt',
    slug: 1,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 2,
    categoryId: 1,
    title: '"Detail H" polo shirt',
    slug: 2,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 3,
    categoryId: 1,
    title: '"Devant cuir empreinte sellier" overshirt',
    slug: 3,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 4,
    categoryId: 1,
    title: 'Fitted shirt with Louis collar',
    slug: 4,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 5,
    categoryId: 1,
    title: '"H" sporty fit embroidered shirt',
    slug: 5,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 6,
    categoryId: 1,
    title: '"H" embroidered T-shirt',
    slug: 6,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 7,
    categoryId: 1,
    title: '"Parcours Sans Faute Decadre" t-shirt',
    slug: 7,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 8,
    categoryId: 1,
    title: '"Piqures sellier" t-shirt',
    slug: 8,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 9,
    categoryId: 1,
    title: 'Polo shirt with pocket',
    slug: 9,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 10,
    categoryId: 1,
    title: 'Saint Germain fitted pants',
    slug: 10,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 11,
    categoryId: 1,
    title: 'Straight cut jeans',
    slug: 11,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 12,
    categoryId: 2,
    title: '18-3-7 scarf 90',
    slug: 12,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 13,
    categoryId: 2,
    title: 'A Toute Berline ! leather eyelet scarf 70',
    slug: 13,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 14,
    categoryId: 2,
    title: 'Brides de Gala Tattoo Cotton Appliqué scarf 90',
    slug: 14,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 15,
    categoryId: 2,
    title: 'Emile et Une Nuit scarf 90',
    slug: 15,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 16,
    categoryId: 2,
    title: 'Emile et Une Nuit scarf 90',
    slug: 16,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 17,
    categoryId: 2,
    title: 'Figures Libres Twilly',
    slug: 17,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 18,
    categoryId: 2,
    title: 'Mystere au 24 scarf 90',
    slug: 18,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 19,
    categoryId: 2,
    title: 'Rayee H stole',
    slug: 19,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 20,
    categoryId: 2,
    title: 'Ready… Go! scarf 45',
    slug: 20,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 21,
    categoryId: 2,
    title: 'Stately Wheels scarf 90',
    slug: 21,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 22,
    categoryId: 3,
    title: '"Bolduc au Carre" micro t-shirt',
    slug: 22,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 23,
    categoryId: 3,
    title: '"Coaching Deja Vu" short-sleeve twillaine sweater',
    slug: 23,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },

  {
    id: 24,
    categoryId: 3,
    title: '"Coaching" long-sleeve cardigan',
    slug: 24,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 25,
    categoryId: 3,
    title: '"Coaching Remix" maxi t-shirt',
    slug: 25,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 26,
    categoryId: 3,
    title: 'Embroidered long poncho vest.webp',
    slug: 26,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 27,
    categoryId: 3,
    title: '"En Desordre Finesse" belted caftan',
    slug: 27,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 28,
    categoryId: 3,
    title: 'Fit sweatshirt',
    slug: 28,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 29,
    categoryId: 3,
    title: 'Jacket with leather detail',
    slug: 29,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 30,
    categoryId: 3,
    title: 'Micro shirt',
    slug: 30,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 31,
    categoryId: 3,
    title: '"Mors a Jouets" embroidered long-sleeve sweater',
    slug: 31,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 32,
    categoryId: 3,
    title: '"Mors a Jouets" t-shirt',
    slug: 32,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 33,
    categoryId: 3,
    title: '"Mosaique" prairie dress',
    slug: 33,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 34,
    categoryId: 4,
    title: 'Alessandro loafer',
    slug: 34,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 35,
    categoryId: 4,
    title: 'Bouncing sneaker',
    slug: 35,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 36,
    categoryId: 4,
    title: 'Chypre sandal',
    slug: 36,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 37,
    categoryId: 4,
    title: 'Deep sneaker',
    slug: 37,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 38,
    categoryId: 4,
    title: 'Eze 30 sandal',
    slug: 38,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 39,
    categoryId: 4,
    title: 'Fresh ankle boot',
    slug: 39,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 40,
    categoryId: 4,
    title: 'Heros sneaker',
    slug: 40,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 41,
    categoryId: 4,
    title: 'Jimmy sneaker',
    slug: 41,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 42,
    categoryId: 4,
    title: 'Job loafer',
    slug: 42,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 43,
    categoryId: 4,
    title: 'Jupiter sandal',
    slug: 43,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 44,
    categoryId: 4,
    title: 'Kelly ballet flat',
    slug: 44,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 45,
    categoryId: 4,
    title: 'Kichu ballet flat',
    slug: 45,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 46,
    categoryId: 4,
    title: 'Kristen sandal',
    slug: 46,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 47,
    categoryId: 4,
    title: 'Oasis sandal',
    slug: 47,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 48,
    categoryId: 4,
    title: 'Oz mule',
    slug: 48,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 49,
    categoryId: 5,
    title: 'Bonnie Lift beret',
    slug: 49,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 50,
    categoryId: 5,
    title: 'Fred Punk H bucket hat',
    slug: 50,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 51,
    categoryId: 5,
    title: 'Harper Emile Hermès bucket hat',
    slug: 51,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 52,
    categoryId: 5,
    title: 'Harper Point Avalon bucket hat',
    slug: 52,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 53,
    categoryId: 5,
    title: 'Ionis Stripes hat',
    slug: 53,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 54,
    categoryId: 5,
    title: 'Jane Love bucket hat',
    slug: 54,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 55,
    categoryId: 5,
    title: 'Julia Naoussa beanie',
    slug: 55,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 56,
    categoryId: 5,
    title: 'Nevada Etriers cap',
    slug: 56,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 57,
    categoryId: 5,
    title: 'Nevada H Stripe cap',
    slug: 57,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
  {
    id: 58,
    categoryId: 5,
    title: 'Serena Lift cap',
    slug: 58,
    available: ['IN', 'CA', 'US', 'JP', 'AE', 'CN', 'GB'],
    specs: {
      price: 199.0,
      salePrice: 174.75,
      saleProfit: 32.5,
      shippingType: 3,
      cost: 20.5,
    },
    stock: {
      IN: 23,
      CA: 45,
      US: 32,
      JP: 123,
      AE: 312,
      CN: 12,
      GB: 32,
    },
  },
];
