export const products = [
  {
    id: 1,
    categoryId: 1,
    title: "Men's Cotton Dark Blue Shirt",
    slug: 1,
    available: ['IN', 'CA'],
    price: 199.0,
    discount: 25.25,
    specs: {
      price: 199.0,
      discount: 25.25,
      salePrice: 174.75,
      saleProfit: 32,
      shippingType: 3,
      cost: 23,
    },
    stock: {
      IN: 23,
      CA: 45,
    },
  },
  {
    id: 2,
    categoryId: 1,
    title: 'Mens Plain Cotton Sky Blue Shirt',
    slug: 2,
    available: ['IN'],
    specs: {
      price: 1234.0,
      discount: 251.25,
      salePrice: 1000.75,
      saleProfit: 298,
      shippingType: 2,
      cost: 321,
    },
    stock: {
      IN: 642,
    },
  },
  {
    id: 3,
    categoryId: 1,
    title: 'Mens Designer Textured Short - White',
    slug: 3,
    available: ['IN'],
    specs: {
      price: 876.0,
      discount: 251.25,
      salePrice: 657.75,
      saleProfit: 123,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 10,
    },
  },
  {
    id: 4,
    categoryId: 2,
    title: 'Dual Color Leather Shoes - Dark Blue, White',
    slug: 4,
    available: ['IN'],
    specs: {
      price: 431.0,
      discount: 21.25,
      salePrice: 81.75,
      saleProfit: 2,
      shippingType: 2,
      cost: 4,
    },
    stock: {
      IN: 29,
    },
  },
  {
    id: 5,
    categoryId: 2,
    title: 'Dual Tone Leather Shoes - High Sole - Orange',
    slug: 5,
    available: ['IN'],
    specs: {
      price: 5000.0,
      discount: 251.25,
      salePrice: 4000.75,
      saleProfit: 1000,
      shippingType: 3,
      cost: 500,
    },
    stock: {
      IN: 800,
    },
  },
  {
    id: 6,
    categoryId: 2,
    title: 'Trendy Sneakers - Dual Blue Contrast',
    slug: 6,
    available: ['IN'],
    specs: {
      price: 100.0,
      discount: 20.25,
      salePrice: 60.75,
      saleProfit: 50,
      shippingType: 1,
      cost: 0,
    },
    stock: {
      IN: 23000,
    },
  },
  {
    id: 7,
    categoryId: 3,
    title: 'Mens Standard Bracelet Silver Gold',
    slug: 7,
    available: ['IN'],
    specs: {
      price: 1234.0,
      discount: 251.25,
      salePrice: 1000.75,
      saleProfit: 298,
      shippingType: 2,
      cost: 321,
    },
    stock: {
      IN: 23,
    },
  },
  {
    id: 8,
    categoryId: 3,
    title: 'Leather Strap Premium Keyring - 987',
    slug: 8,
    available: ['IN'],
    specs: {
      price: 1234.0,
      discount: 251.25,
      salePrice: 1000.75,
      saleProfit: 298,
      shippingType: 2,
      cost: 321,
    },
    stock: {
      IN: 23,
    },
  },
  {
    id: 9,
    categoryId: 3,
    title: 'Light Double String Bracelet with Silver Joint',
    slug: 9,
    available: ['IN'],
    specs: {
      price: 1234.0,
      discount: 251.25,
      salePrice: 1000.75,
      saleProfit: 298,
      shippingType: 2,
      cost: 321,
    },
    stock: {
      IN: 23,
    },
  },
];
